In [2]:
import sys
import os

# Add the project root directory to the Python path
project_root = os.path.abspath("..")  # Adjust based on your folder structure
sys.path.append(project_root)

In [144]:
import torch
import torch.nn as nn
import torch.optim as optim
import importlib
from collections import deque
import random
import numpy as np
from tactix.utils import *
from tactix.tactixEnvironment_without_opp import TactixEnvironment
from tactix.tactixGame import TactixGame
from scripts_1.dqn_agent_masked import DQNAgent as DQNAgentMasked
from scripts.dqn_agent_attention import DQNAgent
from scripts.dqn_agent_mh_attention import DQNAgent as DQNAgentMH
from scripts.dqn_agent_dr_re_attention import DQNAgent as DQNAgentDR
from scripts.train_without_opp_move_attention_mcts2 import TrainAndPlot_without_opp_move_attention_mcts2
from scripts.dqn_attention import DQN
import matplotlib.pyplot as plt

importlib.reload(sys.modules['tactix.tactixGame'])
importlib.reload(sys.modules['tactix.tactixEnvironment_without_opp'])
importlib.reload(sys.modules['tactix.utils'])


<module 'tactix.utils' from '/Users/alibal/Desktop/tactix-game/tactix/utils.py'>

In [47]:
evaluated_model_path_3x3_small = os.path.join(
        project_root,
        "training_results",
        "training_results_3x3_with_attention_mcts2",
        "models",
        "network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_10_mcts_lr_0.4_wr_76_tr_-22962.pth"
    )
print(evaluated_model_path_3x3_small)

/Users/alibal/Desktop/tactix-game/training_results/training_results_3x3_with_attention_mcts2/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_10_mcts_lr_0.4_wr_76_tr_-22962.pth


In [48]:
evaluated_model_path_small = os.path.join(
        project_root,
        "training_results",
        "training_results_5x5_with_attention_mcts2",
        "models",
        "network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_50_mcts_lr_0.4_wr_29_tr_-179250.pth"
    )
print(evaluated_model_path_small)


/Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_50_mcts_lr_0.4_wr_29_tr_-179250.pth


In [49]:
evaluated_agent_small = DQNAgent(state_size=25, action_size=125, layer_sizes=[128, 128, 128],
                           lr=1e-4, gamma=0.7, epsilon_start=0.0, epsilon_end=0.0, epsilon_decay=0.9995,
                           memory_capacity=50000, device="cpu", pretrained_model_path=evaluated_model_path_small)

Loaded pretrained model from /Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_50_mcts_lr_0.4_wr_29_tr_-179250.pth


In [50]:
evaluated_model_path_medium = os.path.join(
        project_root,
        "training_results",
        "training_results_5x5_with_attention_mcts2",
        "models",
        "network_hl_256_256_256_256_256_gamma_0.70_bs_256_tufq_200_mcts_iter_5_mcts_lr_0.4_wr_54_tr_-178538.pth"
    )
print(evaluated_model_path_medium)

/Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_256_256_256_256_256_gamma_0.70_bs_256_tufq_200_mcts_iter_5_mcts_lr_0.4_wr_54_tr_-178538.pth


In [51]:
evaluated_model_path_end_game = os.path.join(
        project_root,
        "training_results",
        "training_results_5x5_with_attention_mcts2",
        "models",
        "network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_50_mcts_lr_0.4_wr_36_tr_-279934.pth"
    )
print(evaluated_model_path_end_game)

/Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_50_mcts_lr_0.4_wr_36_tr_-279934.pth


In [52]:
evaluated_agent_end_game = DQNAgent(state_size=25, action_size=125, layer_sizes=[128, 128, 128],
                           lr=1e-4, gamma=0.75, epsilon_start=0.0, epsilon_end=0.0, epsilon_decay=0.9995,
                           memory_capacity=50000, device="cpu", pretrained_model_path=evaluated_model_path_end_game)

Loaded pretrained model from /Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_50_mcts_lr_0.4_wr_36_tr_-279934.pth


In [53]:
evaluated_model_path_dqn_trained = os.path.join(
        project_root,
        "training_results",
        "training_results_5x5_dqns_against_each_other",
        "models",
        "network_hl_128_128_128_gamma_0.70_bs_128_tufq_100_wr_96_tr_114516.pth"
    )
print(evaluated_model_path_dqn_trained)

/Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_dqns_against_each_other/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_100_wr_96_tr_114516.pth


In [54]:
evaluated_agent_dqn = DQNAgent(state_size=25, action_size=125, layer_sizes=[128, 128, 128],
                           lr=1e-4, gamma=0.7, epsilon_start=0.0, epsilon_end=0.0, epsilon_decay=0.9995,
                           memory_capacity=50000, device="cpu", pretrained_model_path=evaluated_model_path_dqn_trained)

Loaded pretrained model from /Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_dqns_against_each_other/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_100_wr_96_tr_114516.pth


In [55]:
evaluated_agent_medium = DQNAgent(state_size=25, action_size=125, layer_sizes=[256, 256, 256, 256, 256],
                           lr=1e-4, gamma=0.7, epsilon_start=0.0, epsilon_end=0.0, epsilon_decay=0.9995,
                           memory_capacity=50000, device="cpu", pretrained_model_path=evaluated_model_path_medium)

Loaded pretrained model from /Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_256_256_256_256_256_gamma_0.70_bs_256_tufq_200_mcts_iter_5_mcts_lr_0.4_wr_54_tr_-178538.pth


In [56]:
evaluated_model_path_big = os.path.join(
        project_root,
        "training_results",
        "training_results_5x5_with_attention_mcts2",
        "models",
        "network_hl_512_512_512_512_512_512_512_gamma_0.70_bs_512_tufq_200_mcts_iter_5_mcts_lr_0.4_wr_47_tr_-104389.pth"
    )
print(evaluated_model_path_big)

/Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_512_512_512_512_512_512_512_gamma_0.70_bs_512_tufq_200_mcts_iter_5_mcts_lr_0.4_wr_47_tr_-104389.pth


In [57]:
evaluated_agent_big = DQNAgentMH(state_size=25, action_size=125, layer_sizes=[512, 512, 512, 512, 512, 512, 512],
                           lr=1e-4, gamma=0.7, epsilon_start=0.0, epsilon_end=0.0, epsilon_decay=0.9995,
                           memory_capacity=50000, device="cpu", pretrained_model_path=evaluated_model_path_big)

Loaded pretrained model from /Users/alibal/Desktop/tactix-game/training_results/training_results_5x5_with_attention_mcts2/models/network_hl_512_512_512_512_512_512_512_gamma_0.70_bs_512_tufq_200_mcts_iter_5_mcts_lr_0.4_wr_47_tr_-104389.pth


/Users/alibal/Desktop/tactix-game/scripts/dqn_agent_mh_attention.py:39: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.q_network.load_state_dict(torch.load(pretrained_mo

In [58]:
evaluated_agent_small_3x3 = DQNAgent(state_size=9, action_size=27, layer_sizes=[128, 128, 128],
                           lr=1e-4, gamma=0.7, epsilon_start=0.0, epsilon_end=0.0, epsilon_decay=0.9995,
                           memory_capacity=25000, device="cpu", pretrained_model_path=evaluated_model_path_3x3_small)

Loaded pretrained model from /Users/alibal/Desktop/tactix-game/training_results/training_results_3x3_with_attention_mcts2/models/network_hl_128_128_128_gamma_0.70_bs_128_tufq_200_mcts_iter_10_mcts_lr_0.4_wr_76_tr_-22962.pth


In [91]:
game3 = TactixGame(height=3, width=3, np_pieces=np.array([[1,1,0],
                                                          [1,1,0],
                                                          [1,0,0],]))


In [97]:
pieces = game3.getPieces()
pieces

array([[1, 1, 0],
       [1, 1, 0],
       [1, 0, 0]])

In [100]:
pieces = torch.from_numpy(np.array(pieces, dtype=np.float32))
pieces = pieces.view(-1).unsqueeze(0)
pieces


tensor([[1., 1., 0., 1., 1., 0., 1., 0., 0.]])

In [101]:
pieces = pieces.reshape(3,3)
pieces

tensor([[1., 1., 0.],
        [1., 1., 0.],
        [1., 0., 0.]])

In [102]:
pieces.shape

torch.Size([3, 3])

In [152]:
env5 = TactixEnvironment(board_size=5)

In [153]:
env5.reset()

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [154]:
env5.game.display()

 -----------------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
 -----------------------
Current player: -1
Game continues, no winner yet.


In [155]:
env5.step(5)
env5.game.display()

 -----------------------
[[1 0 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
 -----------------------
Current player: 1
Game continues, no winner yet.


In [156]:
validler = env5._generate_valid_moves_mask()
validler

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [157]:
dqn_masked = DQNAgentMasked(state_size=25, action_size=125, layer_sizes=[128, 128, 128])

In [158]:
state = env5._get_observation()
print(state)

tensor([[1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [ ]:
# with torch.no_grad():  
#             temp_next_q_values = self.target_network(next_states)
#             assert temp_next_q_values.shape == next_states_valid_moves_mask.shape
#             temp_next_q_values[next_states_valid_moves_mask == 0] = float('inf')
#             max_next_q_values = temp_next_q_values.min(1)[0]
#             # max_next_q_values = self.target_network(next_states).max(1)[0]
#             target_q_values = rewards + (1 - dones.float()) * self.gamma * max_next_q_values

In [159]:
state = state.view(-1).unsqueeze(0)
state

tensor([[1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])

In [160]:
validler = validler.view(-1).unsqueeze(0)

In [161]:
 qs = dqn_masked.target_network(state)
qs

tensor([[-1.2560e-02,  4.4743e-02, -8.3335e-02, -1.5040e-02, -1.8834e-01,
         -7.6102e-02, -7.4764e-02,  2.8904e-02, -1.2136e-01,  5.9650e-02,
         -1.9152e-04,  2.7374e-02,  1.7062e-02, -4.4029e-02, -1.9325e-03,
         -1.0993e-01, -8.8226e-02,  9.2174e-02,  4.4580e-02,  5.0101e-02,
         -1.7164e-04,  7.5247e-02, -1.1153e-01, -5.8896e-02, -2.8726e-02,
          4.0087e-02, -7.5686e-02, -2.7176e-02,  1.9063e-02, -2.3679e-02,
         -1.4745e-02,  3.7237e-02,  3.0449e-02, -1.4795e-01,  1.1664e-02,
         -6.3705e-02,  2.6341e-02, -5.9780e-02,  5.7212e-02,  8.4586e-02,
         -2.3652e-02, -8.0456e-02, -1.2380e-01, -5.0906e-02,  1.1485e-01,
          7.8896e-02, -6.0614e-02, -7.4042e-02, -7.7887e-02,  7.0329e-02,
         -1.2664e-02,  2.8458e-02, -2.2329e-02, -6.0761e-02, -1.1021e-02,
         -1.6348e-01, -8.3803e-02,  2.4966e-03,  7.9257e-02,  3.3957e-03,
          3.6469e-02,  2.0491e-02,  1.5299e-02,  9.9019e-02, -7.4731e-02,
         -4.5315e-02, -7.4262e-02, -4.

In [162]:
qs[validler == 0] = float('inf')
qs

tensor([[-1.2560e-02,         inf,         inf,         inf,         inf,
                 inf,         inf,         inf,         inf,  5.9650e-02,
         -1.9152e-04,  2.7374e-02,  1.7062e-02, -4.4029e-02, -1.9325e-03,
         -1.0993e-01, -8.8226e-02,  9.2174e-02,  4.4580e-02,  5.0101e-02,
         -1.7164e-04,  7.5247e-02, -1.1153e-01, -5.8896e-02, -2.8726e-02,
          4.0087e-02, -7.5686e-02, -2.7176e-02,  1.9063e-02, -2.3679e-02,
         -1.4745e-02,  3.7237e-02,  3.0449e-02, -1.4795e-01,  1.1664e-02,
         -6.3705e-02,  2.6341e-02, -5.9780e-02,  5.7212e-02,  8.4586e-02,
         -2.3652e-02, -8.0456e-02, -1.2380e-01, -5.0906e-02,  1.1485e-01,
          7.8896e-02, -6.0614e-02, -7.4042e-02, -7.7887e-02,  7.0329e-02,
         -1.2664e-02,  2.8458e-02, -2.2329e-02, -6.0761e-02, -1.1021e-02,
         -1.6348e-01, -8.3803e-02,  2.4966e-03,  7.9257e-02,  3.3957e-03,
          3.6469e-02,  2.0491e-02,  1.5299e-02,  9.9019e-02, -7.4731e-02,
         -4.5315e-02, -7.4262e-02, -4.

In [163]:
q = qs.min(1)[0]
q 

tensor([-0.1782], grad_fn=<MinBackward0>)

In [92]:
env3 = TactixEnvironment(board_size=3)
env3.game = game3
env3.state = env3.game.getPieces()

In [93]:
dqn_gets_state = env3._get_observation()
dqn_gets_valid_moves = env3._generate_valid_moves_mask()

dqn_gets_state = dqn_gets_state.view(-1).unsqueeze(0)       # flatten the state and add a batch dimension
dqn_gets_valid_moves = dqn_gets_valid_moves.unsqueeze(0)  

In [94]:
action_idx = evaluated_agent_small_3x3.select_action(dqn_gets_state, dqn_gets_valid_moves)
print(action_idx)
decoded_action = decode_action(action_idx, 3)
print(decoded_action)

21
[0, 1, 2, True]


In [24]:
game = TactixGame(height=5, width=5, np_pieces=np.array([[0,0,0,0,0],
                                                         [0,1,0,0,0],
                                                         [0,0,0,0,0],
                                                         [1,0,0,0,0],
                                                         [1,0,0,0,0]]))

In [25]:
env = TactixEnvironment(board_size=5)
env.game = game
env.state = env.game.getPieces()

In [26]:
dqn_gets_state = env._get_observation()
dqn_gets_valid_moves = env._generate_valid_moves_mask()

dqn_gets_state = dqn_gets_state.view(-1).unsqueeze(0)       # flatten the state and add a batch dimension
dqn_gets_valid_moves = dqn_gets_valid_moves.unsqueeze(0)    # add a batch dimension

In [27]:
action_idx = evaluated_agent_small.select_action(dqn_gets_state, dqn_gets_valid_moves)
print(action_idx)
decoded_action = decode_action(action_idx, 5)
print(decoded_action)

45
[3, 0, 1, False]


In [523]:
action_idx = evaluated_agent_big.select_action(dqn_gets_state, dqn_gets_valid_moves)
print(action_idx)
decoded_action = decode_action(action_idx, 5)
print(decoded_action)

79
[1, 0, 2, True]


In [483]:
action_idx = evaluated_agent_end_game.select_action(dqn_gets_state, dqn_gets_valid_moves)
print(action_idx)
decoded_action = decode_action(action_idx, 5)
print(decoded_action)

40
[2, 2, 2, False]


In [476]:
action_idx = evaluated_agent_medium.select_action(dqn_gets_state, dqn_gets_valid_moves)
print(action_idx)
decoded_action = decode_action(action_idx, 5)
print(decoded_action)

27
[1, 3, 1, False]


In [478]:
action_idx = evaluated_agent_dqn.select_action(dqn_gets_state, dqn_gets_valid_moves)
print(action_idx)
decoded_action = decode_action(action_idx, 5)
print(decoded_action)

44
[2, 4, 1, False]
